### ISSUE TITLE
Robot crashes and spam bugs

### ISSUE THREAD

**Issue by GardoTL** [ValentinLvrr/Binance-Telegram-Bot#2]
The bot crashes when the scan starts.

```
C:\Users\User\Desktop\Binance-Telegram-Bot-main\commands\startbot.js:49
  for (let trade of trades) {
                    ^

TypeError: trades is not iterable
    at Timeout._onTimeout (C:\Users\User\Desktop\Binance-Telegram-Bot-main\commands\startbot.js:49:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.0
```

There is also another problem, the bot spams the same alerts and also announces each time the trade close identical to the trade open.

![image](https://user-images.githubusercontent.com/90606692/233732929-4522e967-2ba6-46df-8224-aa73e9b4eaaa.png)

**Comment by GardoTL** [comment]
Ty bro !

**Comment by Klayvann** [comment]
Same issue with the crash and spam :( I tried to fix the issue but I don't really understand the code

**Comment by GardoTL** [comment]
still not fixed :(
